### ISSUE TITLE
Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by geepie** [mcguffin/multisite-blog-alias#5]
CREATE TABLE wp_alias_domains (
			`ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
			`created` datetime NOT NULL default '0000-00-00 00:00:00',
			`site_id` bigint(20) unsigned NOT NULL,
			`blog_id` bigint(20) unsigned NOT NULL,
			`domain_alias` varchar(200) NOT NULL,
			`domain_alias_utf8` varchar(200) NOT NULL,
			`redirect` tinyint(2) NOT NULL default '1',
			PRIMARY KEY (`ID`),
			UNIQUE KEY `domain_alias` (`domain_alias`)
		) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci

I think "`domain_alias_utf8` varchar(200)" is too long.

`domain_alias` varchar(180) NOT NULL, `domain_alias_utf8` varchar(180) NOT NULL
is good

**Comment by mcguffin** [comment]
Hi @geepie,
Thanks for the report! I could finally reproduce the issue in a MySQL 5.5 DB using InnoDB.
Setting the charset of `domain_alias` to plain ascii finally did it.
(Additionally the column sizes should be increased to the [maximum domain name length of 253 chars](https://webmasters.stackexchange.com/questions/16996/maximum-domain-name-length)).

This one worked well:
```sql
CREATE TABLE wp_alias_domains (
	`ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
	`created` datetime NOT NULL default '0000-00-00 00:00:00',
	`site_id` bigint(20) unsigned NOT NULL,
	`blog_id` bigint(20) unsigned NOT NULL,
	`domain_alias` varchar(255) CHARACTER SET ascii NOT NULL,
	`domain_alias_utf8` varchar(255) NOT NULL,
	`redirect` tinyint(2) NOT NULL default '1',
	PRIMARY KEY (`ID`),
	UNIQUE KEY `domain_alias` (`domain_alias`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

I'll release an update some later today...
Regards,
Jörn
