### ISSUE TITLE
query_string

### ISSUE THREAD

**Issue by geepie** [mcguffin/multisite-blog-alias#6]
I activate : define('WPMU_BLOG_ALIAS_REDIRECT_WITH_PATH', true);

blog_alias_site_not_found( $current_site, $domain, $path )
I would like the function to transfer the query_string too. How to achieve it ?
I would like the function to redirect to canonical_url. How to achieve it ?

My permalink is https://my_long_domain.com/%post_name%
My use case, I have too domain and I want to have a short_url redirection
http://sho.rt/1234?var=xyz -> https://my_long_domain.com/the_seo_optimized_title/?var=xyz

I want only one redirection. Now I got (post_id = 1234)
http://sho.rt/1234?var=xyz -> https://my_long_domain.com/1234 (your plugin, lost the query_string)
https://my_long_domain.com/1234 -> https://my_long_domain.com/?p=1234 (apache RewriteRule PassThru)
https://my_long_domain.com/?p=1234 -> https://my_long_domain.com/the_seo_optimized_title/

I would appreciate to have
http://sho.rt/1234?var=xyz  -> http://sho.rt/?p=1234&var=xyz (RewriteRule PT)
http://sho.rt/?p=1234&var=xyz -> https://my_long_domain.com/the_seo_optimized_title/?var=xyz

**Comment by mcguffin** [comment]
The plugin is hooking into `ms_site_not_found` which is fired long before WP is parsing the current URL. Not even current blog ID is known at this point.
So, I think limiting to only 2 redirects is not possible.

What you can do, is edit `wp-content/sunrise.php`, and wrap you own logic around the plugins hook callback:

```php
// [...]
//END:multisite-blog-alias//

if ( function_exists( 'blog_alias_site_not_found' ) ) {
	remove_action( 'ms_site_not_found', 'blog_alias_site_not_found' );
	add_action( 'ms_site_not_found', function( $current_site, $domain, $path ) {
		// append query string to redirect $path
		if ( isset( $_SERVER['QUERY_STRING'] ) && ! empty( $_SERVER['QUERY_STRING'] ) ) {
			$path .= '?' . $_SERVER['QUERY_STRING'];
		}
		blog_alias_site_not_found(  $current_site, $domain, $path );
	}, 10, 3 );
}
```
